services:
  satisfactory-server:
    container_name: 'satisfactory-server'
    hostname: 'satisfactory-server'
    image: 'wolveix/satisfactory-server:latest'
    ports:
      - '7777:7777/udp'
      - '7777:7777/tcp'
      - '8888:8888/tcp'
    volumes:
      - './satisfactory-server:/config'
    environment:
      - MAXPLAYERS=4
      - PGID=1000
      - PUID=1000
      - STEAMBETA=false
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 10G
        reservations:
          memory: 8G
  satisfactory-website:
    container_name: 'satisfactory-website'
    image: localhost:5000/satisfactory-website:latest
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - './satisfactory-server/saved/server:/usr/share/nginx/html/saves:ro'
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.satisfactory-map.rule=Host(`satisfactory.jamiepenney.co.nz`)"
      - "traefik.http.routers.satisfactory-map.entrypoints=https"
      - "traefik.http.routers.satisfactory-map.tls=true"
      - "traefik.http.routers.satisfactory-map.tls.certresolver=letsencrypt"
  # Container that runs a crontab that creates a symlink to the latest save
  save-games:
    container_name: 'satisfactory-save-games'
    restart: unless-stopped
    image: localhost:5000/satisfactory-save-games:latest
    volumes:
      - './satisfactory-server/saved/server:/saves'

networks:
  traefik:
    name: traefik
    external: true
