name: Build and deploy
on:
  push:
    branches: [ main ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Get node_modules cache
        uses: actions/cache@v4
        id: node_modules
        with:
          path: |
            **/node_modules
          # Add node version as a cache key to avoid yarn recompilation for particular node as it doesn't change often
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}-${{ steps.node.outputs.version }}
      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile
      - name: Build site
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-site
          # Upload only the public directory
          path: './dist'

  # Deployment job
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Download built site
        uses: actions/download-artifact@v4
        with:
          name: built-site
          path: './dist'

      - name: Deploy site
        id: deployment
        run: |
          cp ./dist /opt/satisfactory/website
          cd /opt/satisfactory && docker compose restart
